name: liftaholic_frontend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.0
  google_fonts: ^6.1.0
  image_picker: ^0.8.1+3
  lottie: ^3.0.0
  flutter_login: ^5.0.0
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  table_calendar: ^3.0.9
  intl: ^0.18.1
  flutter_slidable: ^3.0.1
  flutter_riverpod: ^2.4.10
  riverpod: ^2.5.0
  flutter_spinbox: ^0.13.1
  syncfusion_flutter_gauges: ^24.2.8
  flutter_hooks: ^0.20.5
  pedantic_mono: ^1.24.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/google_fonts/
    - .env
  fonts:
    - family: Honk
      fonts:
        - asset: assets/google_fonts/Honk/static/Honk-Regular.ttf