// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANzpj-8RYxUjClhtoEWkwB4vMhnjtNsPE',
    appId: '1:575478419293:web:fad0507c85b3c28a5fe2b4',
    messagingSenderId: '575478419293',
    projectId: 'liftaholic-b6eb8',
    authDomain: 'liftaholic-b6eb8.firebaseapp.com',
    storageBucket: 'liftaholic-b6eb8.appspot.com',
    measurementId: 'G-QFBP4PCH10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPH4dOKvqvStzOrJYM-Qm_j4YfDmqhlQ0',
    appId: '1:575478419293:android:d46efdd12a4ebfe75fe2b4',
    messagingSenderId: '575478419293',
    projectId: 'liftaholic-b6eb8',
    storageBucket: 'liftaholic-b6eb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCGchfrFq_JBdT_nyqAIavqry2KylXwhQ',
    appId: '1:575478419293:ios:8eb5a943c91fc5a85fe2b4',
    messagingSenderId: '575478419293',
    projectId: 'liftaholic-b6eb8',
    storageBucket: 'liftaholic-b6eb8.appspot.com',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCGchfrFq_JBdT_nyqAIavqry2KylXwhQ',
    appId: '1:575478419293:ios:8eb5a943c91fc5a85fe2b4',
    messagingSenderId: '575478419293',
    projectId: 'liftaholic-b6eb8',
    storageBucket: 'liftaholic-b6eb8.appspot.com',
    iosBundleId: 'com.example.flutterApplicationTest',
  );
}
